prometheus:
  additionalServiceMonitors:
    - name: "app-python"
      selector:
        matchLabels:
          app.kubernetes.io/instance: python
      namespaceSelector:
        any: true
      endpoints:
        - port: http
          path: /metrics