# Wipe the web app by deleting all Docker container and all related files
- name: Wipe Web App
  when: web_app_full_wipe
  block:
    - name: Check if docker-compose file exists
      stat:
        path: "{{ docker_compose_file }}"
      register: docker_compose

    - name: Check if web app directory exists
      stat:
        path: "{{ app_path }}"
      register: web_app_directory

    - name: Remove docker containers
      when: docker_compose.stat.exists == true
      command: "docker-compose -p {{ app_name }} down --remove-orphans"
      args:
        chdir: "{{ app_path }}"

    - name: Delete web application directory
      when: web_app_directory.stat.exists == true
      file:
        path: '{{ app_path }}'
        state: absent