# Splitting tasks and running them sequentially
- name: Create Docker Role
  block:
    - name: Pip
      import_tasks: install_pip.yml
    - name: Docker
      import_tasks: install_docker.yml
    - name: Compose
      import_tasks: install_compose.yml