apiVersion: apps/v1

kind: Deployment

metadata:
  name: app-python
  labels:
    app: app-python
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-python
  template:
    metadata:
      labels:
        app: app-python
    spec:
      containers:
        - name: app-python
          image: vladimirka002/innopolis-devops-python-app:latest
          ports:
            - containerPort: 8080